In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X= df.drop('species',axis=1)
y=df['species']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn= KNeighborsClassifier(n_neighbors=5)

In [11]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [12]:
model_knn.score(X_test,y_test)

0.98

In [13]:
from sklearn.svm import SVC

In [14]:
model_svm= SVC(C=30, kernel='rbf',gamma = 'auto')

In [15]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [16]:
model_svm.score(X_test,y_test)

0.98

In [17]:
# grid search cv
from sklearn.model_selection import GridSearchCV

In [19]:
classifier = GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [20]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [22]:
classifier.cv_results_

{'mean_fit_time': array([0.0025001 , 0.00185595, 0.00201616, 0.0016984 , 0.0012404 ,
        0.00060372, 0.00197396, 0.00208049]),
 'std_fit_time': array([0.00048378, 0.00058106, 0.00049496, 0.0005644 , 0.00038975,
        0.00049294, 0.00057225, 0.00060348]),
 'mean_score_time': array([0.00192695, 0.00136328, 0.00180616, 0.00073652, 0.00102973,
        0.00139284, 0.00110707, 0.00063047]),
 'std_score_time': array([5.98257739e-04, 3.68016944e-04, 6.07473858e-04, 4.30205259e-04,
        3.09492663e-05, 2.24862369e-04, 2.03219169e-04, 5.16690293e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7])}

In [26]:
results_svm = pd.DataFrame(classifier.cv_results_)

In [27]:
results_svm

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002500,0.000484,0.001927,0.000598,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001856,0.000581,0.001363,0.000368,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002016,0.000495,0.001806,0.000607,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001698,0.000564,0.000737,0.000430,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001240,0.000390,0.001030,0.000031,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000604,0.000493,0.001393,0.000225,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001974,0.000572,0.001107,0.000203,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002080,0.000603,0.000630,0.000517,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [28]:
results_svm[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [38]:
classifier_knn = GridSearchCV((model_knn),{
    'n_neighbors': [1,3,5,7,9],
    'weights':['uniform','distance'],
},cv=5,return_train_score=False)

In [40]:
classifier_knn.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9],
                         'weights': ['uniform', 'distance']})

In [41]:
classifier_knn.cv_results_

{'mean_fit_time': array([0.00209966, 0.00209122, 0.00146046, 0.        , 0.00172658,
        0.00106382, 0.00414448, 0.00112057, 0.00154409, 0.        ]),
 'std_fit_time': array([0.00070922, 0.00031356, 0.00245049, 0.        , 0.00282236,
        0.00212765, 0.00565772, 0.00191078, 0.00214329, 0.        ]),
 'mean_score_time': array([0.00362377, 0.00169234, 0.00121775, 0.0031486 , 0.0044682 ,
        0.        , 0.00249887, 0.00167928, 0.00260186, 0.00237412]),
 'std_score_time': array([0.00078126, 0.00098743, 0.00149144, 0.00629721, 0.00544568,
        0.        , 0.00207215, 0.00183434, 0.00213616, 0.00474825]),
 'param_n_neighbors': masked_array(data=[1, 1, 3, 3, 5, 5, 7, 7, 9, 9],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 1, 'weights': 'uniform'},
  {'n_neighbors': 1, 'weights': 'distance'},
  {'n_neighbors': 3, 'weights': 'uniform'},
  {'n_neighbors': 3, 'weights': 'distance'},
  {'n_neighbors': 5, 'weights': 'uniform'},
  {'n_neighbors': 5, 'weights': 'distance'},
  {'n_neighbors': 7, 'weights': 'uniform'},
  {'n_neighbors': 7, 'weights': 'distance'},
  {'n_neighbors': 9, 'weights': 'uniform'},
  {'n_neighbors': 9, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.9       , 0.96666667, 0.96666667, 0.96666667, 0.93333333]),
 'split3_test_score': array([0.93333333, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.96      , 0.96666667, 0.96666667, 0.97333333,
        0.96666667, 0.98      , 0.98      , 0.97333333, 0.97333333]),
 'std_test_score': array([0.02494438, 0.02494438, 0.02108185, 0.02108185, 0.02494438,
        0.03651484, 0.01632993, 0.01632993, 0.02494438, 0.02494438]),
 'rank_test_score': array([9, 9, 6, 6, 3, 6, 1, 1, 3, 3])}

In [42]:
results_knn = pd.DataFrame(classifier_svm.cv_results_)

In [43]:
results_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002021,0.000032,0.003882,0.000459,1,uniform,"{'n_neighbors': 1, 'weights': 'uniform'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,9
1,0.002098,0.000142,0.002406,0.000802,1,distance,"{'n_neighbors': 1, 'weights': 'distance'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,9
2,0.001404,0.000491,0.002607,0.000491,3,uniform,"{'n_neighbors': 3, 'weights': 'uniform'}",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,6
3,0.001203,0.000401,0.001805,0.000401,3,distance,"{'n_neighbors': 3, 'weights': 'distance'}",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,6
4,0.001874,0.000706,0.003928,0.000696,5,uniform,"{'n_neighbors': 5, 'weights': 'uniform'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
5,0.001203,0.000402,0.001863,0.000440,5,distance,"{'n_neighbors': 5, 'weights': 'distance'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,6
6,0.001604,0.000491,0.003008,0.000001,7,uniform,"{'n_neighbors': 7, 'weights': 'uniform'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.001203,0.000401,0.001604,0.000491,7,distance,"{'n_neighbors': 7, 'weights': 'distance'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
8,0.001805,0.000401,0.003617,0.000375,9,uniform,"{'n_neighbors': 9, 'weights': 'uniform'}",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,3
9,0.001404,0.000491,0.001604,0.000491,9,distance,"{'n_neighbors': 9, 'weights': 'distance'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3

In [45]:
results_knn[['param_n_neighbors','param_weights','mean_test_score']]

   param_n_neighbors param_weights  mean_test_score
0                  1       uniform         0.960000
1                  1      distance         0.960000
2                  3       uniform         0.966667
3                  3      distance         0.966667
4                  5       uniform         0.973333
5                  5      distance         0.966667
6                  7       uniform         0.980000
7                  7      distance         0.980000
8                  9       uniform         0.973333
9                  9      distance         0.973333

In [46]:
from sklearn.model_selection import RandomizedSearchCV

In [51]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel':['rbf','linear'],
},n_iter = 10 , cv=5,return_train_score=False)

In [52]:
classifier_r.fit(X,y)

c:\Users\jhaki\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:320: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [53]:
results = pd.DataFrame(classifier_r.cv_results_)

In [55]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006762,0.010971,0.001546,0.000406,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002109,0.000720,0.001379,0.000346,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001529,0.000659,0.001529,0.000579,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002086,0.000065,0.001037,0.000057,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001355,0.000454,0.001619,0.000451,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001913,0.000484,0.001246,0.000397,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001300,0.000594,0.001521,0.000539,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001508,0.000593,0.001188,0.000951,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [57]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000