In [2]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X= df.drop('species',axis=1)
y=df['species']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn= KNeighborsClassifier(n_neighbors=5)

In [11]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [12]:
model_knn.score(X_test,y_test)

0.98

In [13]:
from sklearn.svm import SVC

In [14]:
model_svm= SVC(C=30, kernel='rbf',gamma = 'auto')

In [15]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [16]:
model_svm.score(X_test,y_test)

0.98

In [17]:
# grid search cv
from sklearn.model_selection import GridSearchCV

In [18]:
classifier = GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [19]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [20]:
classifier.cv_results_

{'mean_fit_time': array([0.00343771, 0.00221167, 0.00210304, 0.0019486 , 0.00162797,
        0.00193229, 0.00191326, 0.00224504]),
 'std_fit_time': array([0.00036806, 0.00014521, 0.00123109, 0.00253518, 0.00149591,
        0.00192161, 0.00103896, 0.00234291]),
 'mean_score_time': array([0.00240693, 0.00128026, 0.00153918, 0.00203848, 0.00188622,
        0.00123   , 0.00152378, 0.00116358]),
 'std_score_time': array([0.00076446, 0.00039374, 0.0011208 , 0.00107833, 0.00137165,
        0.00136067, 0.00095819, 0.00097455]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7])}

In [21]:
results_svm = pd.DataFrame(classifier.cv_results_)

In [22]:
results_svm

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003438,0.000368,0.002407,0.000764,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002212,0.000145,0.001280,0.000394,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002103,0.001231,0.001539,0.001121,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001949,0.002535,0.002038,0.001078,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001628,0.001496,0.001886,0.001372,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001932,0.001922,0.001230,0.001361,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001913,0.001039,0.001524,0.000958,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002245,0.002343,0.001164,0.000975,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [23]:
results_svm[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [24]:
classifier_knn = GridSearchCV((model_knn),{
    'n_neighbors': [1,3,5,7,9],
    'weights':['uniform','distance'],
},cv=5,return_train_score=False)

In [25]:
classifier_knn.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9],
                         'weights': ['uniform', 'distance']})

In [26]:
classifier_knn.cv_results_

{'mean_fit_time': array([0.00212498, 0.00245771, 0.00264459, 0.00117426, 0.00090699,
        0.00186906, 0.00131807, 0.00295029, 0.0010375 , 0.0031877 ]),
 'std_fit_time': array([0.00205169, 0.00045858, 0.00175547, 0.00100759, 0.00091492,
        0.00118658, 0.00118699, 0.00277243, 0.00110745, 0.00321212]),
 'mean_score_time': array([0.00454979, 0.00432277, 0.00392246, 0.00334692, 0.00434003,
        0.00289922, 0.00350809, 0.        , 0.00317149, 0.00063667]),
 'std_score_time': array([0.00287914, 0.00040471, 0.00095708, 0.00260967, 0.00059149,
        0.0021654 , 0.00121986, 0.        , 0.00291096, 0.00082214]),
 'param_n_neighbors': masked_array(data=[1, 1, 3, 3, 5, 5, 7, 7, 9, 9],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 1, 'weights': 'uniform'},
  {'n_neighbors': 1, 'weights': 'distance'},
  {'n_neighbors': 3, 'weights': 'uniform'},
  {'n_neighbors': 3, 'weights': 'distance'},
  {'n_neighbors': 5, 'weights': 'uniform'},
  {'n_neighbors': 5, 'weights': 'distance'},
  {'n_neighbors': 7, 'weights': 'uniform'},
  {'n_neighbors': 7, 'weights': 'distance'},
  {'n_neighbors': 9, 'weights': 'uniform'},
  {'n_neighbors': 9, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.9       , 0.96666667, 0.96666667, 0.96666667, 0.93333333]),
 'split3_test_score': array([0.93333333, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.96      , 0.96666667, 0.96666667, 0.97333333,
        0.96666667, 0.98      , 0.98      , 0.97333333, 0.97333333]),
 'std_test_score': array([0.02494438, 0.02494438, 0.02108185, 0.02108185, 0.02494438,
        0.03651484, 0.01632993, 0.01632993, 0.02494438, 0.02494438]),
 'rank_test_score': array([9, 9, 6, 6, 3, 6, 1, 1, 3, 3])}

In [27]:
results_knn = pd.DataFrame(classifier_knn.cv_results_)

In [28]:
results_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002125,0.002052,0.004550,0.002879,1,uniform,"{'n_neighbors': 1, 'weights': 'uniform'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,9
1,0.002458,0.000459,0.004323,0.000405,1,distance,"{'n_neighbors': 1, 'weights': 'distance'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,9
2,0.002645,0.001755,0.003922,0.000957,3,uniform,"{'n_neighbors': 3, 'weights': 'uniform'}",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,6
3,0.001174,0.001008,0.003347,0.002610,3,distance,"{'n_neighbors': 3, 'weights': 'distance'}",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,6
4,0.000907,0.000915,0.004340,0.000591,5,uniform,"{'n_neighbors': 5, 'weights': 'uniform'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
5,0.001869,0.001187,0.002899,0.002165,5,distance,"{'n_neighbors': 5, 'weights': 'distance'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,6
6,0.001318,0.001187,0.003508,0.001220,7,uniform,"{'n_neighbors': 7, 'weights': 'uniform'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.002950,0.002772,0.000000,0.000000,7,distance,"{'n_neighbors': 7, 'weights': 'distance'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
8,0.001038,0.001107,0.003171,0.002911,9,uniform,"{'n_neighbors': 9, 'weights': 'uniform'}",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,3
9,0.003188,0.003212,0.000637,0.000822,9,distance,"{'n_neighbors': 9, 'weights': 'distance'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3

In [29]:
results_knn[['param_n_neighbors','param_weights','mean_test_score']]

   param_n_neighbors param_weights  mean_test_score
0                  1       uniform         0.960000
1                  1      distance         0.960000
2                  3       uniform         0.966667
3                  3      distance         0.966667
4                  5       uniform         0.973333
5                  5      distance         0.966667
6                  7       uniform         0.980000
7                  7      distance         0.980000
8                  9       uniform         0.973333
9                  9      distance         0.973333

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel':['rbf','linear'],
},n_iter = 10 , cv=5,return_train_score=False)

In [32]:
classifier_r.fit(X,y)

c:\Users\jhaki\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:320: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [33]:
results = pd.DataFrame(classifier_r.cv_results_)

In [34]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001389,0.000967,0.002223,0.000575,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002205,0.000820,0.000910,0.000190,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001992,0.002538,0.000504,0.000635,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001935,0.001663,0.000000,0.000000,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002762,0.003512,0.000000,0.000000,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000867,0.001066,0.001926,0.003852,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001366,0.001896,0.001970,0.002706,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.000802,0.000982,0.001746,0.002609,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [35]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [36]:
#ensemble model
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns

In [37]:
df = sns.load_dataset('iris')

In [38]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [39]:
#STACKING
X= df.drop('species', axis=1)
y= df['species']

In [40]:
le= LabelEncoder()
y_encoded= le.fit_transform(y)

In [41]:
X_train,X_test, y_train, y_test= train_test_split(X,y_encoded,test_size=0.2, random_state =42, stratify=y_encoded)

In [42]:
base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True, kernel='rbf',random_state=42)),
    ('lr',LogisticRegression(max_iter=1000))
]

In [43]:
meta_learner= LogisticRegression(max_iter=1000)

In [44]:
stacking_clf= StackingClassifier(
    estimators= base_learners,
    final_estimator=meta_learner,
    cv=5
)

In [45]:
stacking_clf.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [46]:
y_pred= stacking_clf.predict(X_test)

In [47]:
accuracy= accuracy_score(y_test,y_pred)

In [48]:
accuracy

0.9666666666666667

In [49]:
# RANDOM FOREST USING BAGGING

from sklearn.ensemble import RandomForestClassifier

In [50]:
rf_model = RandomForestClassifier(
    n_estimators=100,  #no of trees
    max_depth=None,   #let trees grow fully
    random_state=42,

)

In [51]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [52]:
y_pred= rf_model.predict(X_test)

In [53]:
accuracy= accuracy_score(y_test,y_pred)

In [54]:
accuracy

0.9

In [55]:
# BOOSTING

In [56]:
# Ada Boost
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [57]:
ada_model= AdaBoostClassifier(n_estimators=100,random_state=42)

In [58]:
ada_model.fit(X_train,y_train)

c:\Users\jhaki\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

AdaBoostClassifier(n_estimators=100, random_state=42)

In [59]:
y_pred = ada_model.predict(X_test)

In [60]:
accuracy= accuracy_score(y_test, y_pred)

In [61]:
accuracy

0.9

In [62]:
# gradient boosting
gb_model= GradientBoostingClassifier(n_estimators=100, learning_rate=0.1,random_state=42)

In [63]:
gb_model.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [64]:
y_pred= gb_model.predict(X_test)

In [65]:
accuracy = accuracy_score(y_test,y_pred)

In [66]:
accuracy

0.9666666666666667

In [71]:
# xgboost
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\jhaki\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\jhaki\anaconda3\lib\site-packages (from xgboost) (1.13.1)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
    --------------------------------------- 2.4/101.7 MB 13.4 MB/s eta 0:00:08
   -- ------------------------------------- 5.5/101.7 MB 13.4 MB/s eta 0:00:08
   --- ------------------------------------ 8.7/101.7 MB 14.5 MB/s eta 0:00:07
   ----- ---------------------------------- 13.1/101.7 MB 16.1 MB/s eta 0:00:06
   ------- -------------------------------- 18.6/101.7 MB 18.4 MB/s eta 0:00:05
   -------- ------------------------------- 20.7/101.7 MB 17.2 MB/s eta 0:00:05
   -------- ------------------------------- 21.5/101.7 MB 15.3 MB/s eta 0:00:06
   -------- ------------------------------- 22.5/101.7 MB 13.8 MB/s eta 0:00:06
   --------- ------------------------------ 24.1/101.7 MB 13.2 MB/s eta 0:00:06
   ---------- ----------------------------- 26.0/101.7 MB 12.8 MB/s eta 0:00:06
   ----------- ---------------------------- 29.1/101.7 MB 13.0 MB/s eta 0:00:06
   ------------ --------------------------- 32.8/101.7 MB 13.4 MB/s eta 0:00:06
   ------------- -------------------------- 34.9/101.7 MB 13.2 MB/s eta 0:00:06
   -------------- ------------------------- 37.0/101.7 MB 12.9 MB/s eta 0:00:06
   --------------- ------------------------ 39.1/101.7 MB 12.8 MB/s eta 0:00:05
   ---------------- ----------------------- 42.2/101.7 MB 12.8 MB/s eta 0:00:05
   ------------------ --------------------- 45.9/101.7 MB 13.2 MB/s eta 0:00:05
   ------------------- -------------------- 48.8/101.7 MB 13.3 MB/s eta 0:00:04
   -------------------- ------------------- 50.9/101.7 MB 13.2 MB/s eta 0:00:04
   -------------------- ------------------- 51.9/101.7 MB 12.8 MB/s eta 0:00:04
   --------------------- ------------------ 53.7/101.7 MB 12.5 MB/s eta 0:00:04
   ---------------------- ----------------- 56.1/101.7 MB 12.5 MB/s eta 0:00:04
   ----------------------- ---------------- 59.2/101.7 MB 12.6 MB/s eta 0:00:04
   ------------------------ --------------- 63.2/101.7 MB 12.9 MB/s eta 0:00:03
   ------------------------- -------------- 66.1/101.7 MB 12.9 MB/s eta 0:00:03
   -------------------------- ------------- 68.4/101.7 MB 12.9 MB/s eta 0:00:03
   --------------------------- ------------ 70.3/101.7 MB 12.7 MB/s eta 0:00:03
   ---------------------------- ----------- 72.6/101.7 MB 12.7 MB/s eta 0:00:03
   ----------------------------- ---------- 75.5/101.7 MB 12.8 MB/s eta 0:00:03
   ------------------------------ --------- 78.4/101.7 MB 12.8 MB/s eta 0:00:02
   ------------------------------- -------- 80.7/101.7 MB 12.8 MB/s eta 0:00:02
   -------------------------------- ------- 82.6/101.7 MB 12.6 MB/s eta 0:00:02
   --------------------------------- ------ 85.2/101.7 MB 12.6 MB/s eta 0:00:02
   ---------------------------------- ----- 87.8/101.7 MB 12.7 MB/s eta 0:00:02
   ----------------------------------- ---- 90.2/101.7 MB 12.6 MB/s eta 0:00:01
   ------------------------------------ --- 92.8/101.7 MB 12.6 MB/s eta 0:00:01
   ------------------------------------- -- 95.7/101.7 MB 12.7 MB/s eta 0:00:01
   -------------------------------------- - 97.8/101.7 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------  99.4/101.7 MB 12.5 MB/s eta 0:00:01
   --------------------------------------  101.4/101.7 MB 12.5 MB/s eta 0:00:01
   --------------------------------------- 101.7/101.7 MB 12.2 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [72]:
from xgboost import XGBClassifier

In [73]:
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, use_label_encoder=False, eval_metric='mlogloss', random_state=42)

In [74]:
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [76]:
y_pred = xgb_model.predict(X_test)

In [77]:
accuracy= accuracy_score(y_test, y_pred)

In [78]:
accuracy

0.9333333333333333